# Generated by Django 4.1.3 on 2022-12-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='titleMovie',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
