# Generated by Django 4.1.3 on 2022-12-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_review_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('user',)},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='titleReview',
        ),
        migrations.AddField(
            model_name='review',
            name='nota',
            field=models.IntegerField(choices=[(0, '0 Stars'), (1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0),
        ),
    ]
