# Generated by Django 4.1.3 on 2022-12-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_fullname_user_apellidos_user_codregistro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apellidos',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='codregistro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombres',
        ),
    ]
